fix deleting messages in bnc
Senderman/lastkatkabot pull request #13
Opened 2021-04-16 16:18 UTC by drforse

2021-04-16 16:38 UTC, Senderman requested changes
Некоторые методы торчат наружу там где не нужно, что влечет к излишнему зацеплению в коде

2021-04-16 16:38 UTC, Senderman commented on src/main/java/com/senderman/lastkatkabot/bnc/BncDatabaseManager.java
> +    private final BncFloodMessageService floodMessagesDatabase;
Это сервис, а не БД. так и называй, floodMessagesService.

2021-04-16 16:38 UTC, Senderman commented on src/main/java/com/senderman/lastkatkabot/bnc/BncDatabaseManager.java
> +    public void addFloodMessage(int messageId, long chatId) {
Почему этот метод торчит наружу? сюда должно попадать при отправке сообщения. вот пусть метод отправки и торчит. addFloodMessage в интерфейс выводить не надо

2021-04-16 16:38 UTC, Senderman commented on src/main/java/com/senderman/lastkatkabot/bnc/BncDatabaseManager.java
> +    public void deleteFloodMessagesByGameId(long gameId) {
И этот метод не должен быть public

2021-04-16 16:38 UTC, Senderman commented on src/main/java/com/senderman/lastkatkabot/bnc/BncTelegramHandler.java
> +                    telegram, null, exceptionsConsumer::onException, null);
Не нужно, пусть просто молча удаляет. не удалось - и ладно. максимум можно цикл приостановить

2021-04-16 16:46 UTC, drforse commented on src/main/java/com/senderman/lastkatkabot/bnc/BncDatabaseManager.java
> +    private final BncFloodMessageService floodMessagesDatabase;
Я просто следовал "конвенции" заданной тобой же линией выше, ну ок :D

2021-10-14 17:29 UTC, Senderman commented
PR закрыт в связи с тем что данная фича уже реализована + автор не отвечает

2021-10-14 17:29 UTC, closed without merging